config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :docs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
before_action :find_doc,only: [:show, :edit, :update, :destroy]

def index
    @docs = Doc.all.order('created_at DESC')
end

def show
    @doc = Doc.find(params[:id])
end

def new
    @doc = Doc.new
end

def create
    @doc = Doc.new(doc_params)

    if @doc.save
        redirect_to @doc
    else
        render 'new'
    end
end

def edit
end

def update
    if @doc.update(doc_params)
        redirect_to @doc
    else
        render 'edit'
    end
end

def destroy
    @doc.destroy
    redirect_to docs_path
end

    private

        def find_doc
            @doc = Doc.find(params[:id])
        end

        def doc_params
            params.require(:doc).permit(:title, :content)
        end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
    =f.input :title 
    =f.input :content
    =f.button :submit

app/views/docs/edit.html.haml
%h1 Fix your Doc!

= render 'form'

=link_to "Cancel", doc_path

app/views/docs/index.html.haml
- @docs.each do |doc|
    %h2= link_to doc.title, doc
    %p= time_ago_in_words(doc.created_at)
    %p= truncate(doc.content, lenght:500)

    =link_to "Create Doc", new_doc_path 

app/views/docs/new.html.haml
%h1 New Document

= render 'form'

app/views/docs/show.html.haml
%h1= @doc.title
%p= @doc.content

=link_to "All Docs", docs_path 
=link_to "Edit Doc", edit_doc_path(@doc)
=link_to "Trash It", doc_path, method: :delete, data: { confirm: "Are you sure?"}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CABINET</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.haml
%h1 Hello im emi